export const FETCH_FACILITY_TC_LIST = 'FETCH_FACILITY_TC_LIST';
export const FETCH_FACILITY_TC_REQUEST = 'FETCH_FACILITY_TC_REQUEST';
export const FETCH_FACILITY_TC_SUCCESS = 'FETCH_FACILITY_TC_SUCCESS';
export const FETCH_FACILITY_TC_ERROR = 'FETCH_FACILITY_TC_ERROR';
export const FETCH_GET_PACKAGE_BY_CATEGOTY_LIST = 'FETCH_GET_PACKAGE_BY_CATEGOTY_LIST';
export const FETCH_GET_PACKAGE_BY_CATEGOTY_REQUEST = 'FETCH_GET_PACKAGE_BY_CATEGOTY_REQUEST';
export const FETCH_GET_PACKAGE_BY_CATEGOTY_SUCCESS = 'FETCH_GET_PACKAGE_BY_CATEGOTY_SUCCESS';
export const FETCH_GET_PACKAGE_BY_CATEGOTY_ERROR = 'FETCH_GET_PACKAGE_BY_CATEGOTY_ERROR';

export const ROLE = {
  SUPER_ADMIN: 'Super Admin',
  CR: 'CR',
  NOTIFIER: 'Notifier',
  LAUNCHER: 'Launcher',
  MINISTRY_ADMIN: 'Ministry Admin',
  VIEWER: 'Viewer',
  SECONDARY_ADMIN: 'Secondary Admin'
};
