export const FETCH_PACKAGE = 'FETCH_PACKAGE';

export const FETCH_PACKAGE_REQUEST = 'FETCH_PACKAGE_REQUEST';

export const FETCH_PACKAGE_SUCCESS = 'FETCH_PACKAGE_SUCCESS';

export const FETCH_PACKAGE_ERROR = 'FETCH_PACKAGE_ERROR';

export const CREATE_PACKAGE = 'CREATE_PACKAGE';

export const CREATE_PACKAGE_REQUEST = 'CREATE_PACKAGE_REQUEST';

export const CREATE_PACKAGE_SUCCESS = 'CREATE_PACKAGE_SUCCESS';

export const CREATE_PACKAGE_ERROR = 'CREATE_PACKAGE_ERROR';

export const FACILITY_CATEGORY_ERROR = 'Please select a Facility Category';

export const PACKAGE_TYPE_ERROR = 'Please enter a package Type';

export const PACKAGE_DELETE = 'PACKAGE_DELETE';

export const PACKAGE_DELETE_REQUEST = 'PACKAGE_DELETE_REQUEST';

export const PACKAGE_DELETE_SUCCESS = 'PACKAGE_DELETE_SUCCESS';

export const PACKAGE_DELETE_ERROR = 'PACKAGE_DELETE_ERROR';

export const PACKAGE_UPDATE = 'PACKAGE_UPDATE';

export const PACKAGE_UPDATE_REQUEST = 'PACKAGE_UPDATE_REQUEST';

export const PACKAGE_UPDATE_SUCCESS = 'PACKAGE_UPDATE_SUCCESS';

export const PACKAGE_UPDATE_ERROR = 'PACKAGE_UPDATE_ERROR';

export const PACKAGE_CLEAR_STORE = 'PACKAGE_CLEAR_STORE';

export const STATUS_UPDATE_PACKAGE = 'STATUS_UPDATE_PACKAGE';

export const STATUS_UPDATE_PACKAGE_REQUEST = 'STATUS_UPDATE_PACKAGE_REQUEST';

export const STATUS_UPDATE_PACKAGE_SUCCESS = 'STATUS_UPDATE_PACKAGE_SUCCESS';

export const STATUS_UPDATE_PACKAGE_ERROR = 'STATUS_UPDATE_PACKAGE_ERROR';
