export const FETCH_SERVICE = 'FETCH_SERVICE';

export const FETCH_SERVICE_REQUEST = 'FETCH_SERVICE_REQUEST';

export const FETCH_SERVICE_SUCCESS = 'FETCH_SERVICE_SUCCESS';

export const FETCH_SERVICE_ERROR = 'FETCH_SERVICE_ERROR';

export const CREATE_SERVICE = 'CREATE_SERVICE';

export const CREATE_SERVICE_REQUEST = 'CREATE_SERVICE_REQUEST';

export const CREATE_SERVICE_SUCCESS = 'CREATE_SERVICE_SUCCESS';

export const CREATE_SERVICE_ERROR = 'CREATE_SERVICE_ERROR';

export const SERVICE_NAME_ERROR = 'Please enter a Facility Name';

export const FACILITY_CATEGORY_ERROR = 'Please select a Facility Category';

export const SERVICE_TYPE_ERROR = 'Please enter a service Type';

export const SERVICE_DELETE = 'SERVICE_DELETE';

export const SERVICE_DELETE_REQUEST = 'SERVICE_DELETE_REQUEST';

export const SERVICE_DELETE_SUCCESS = 'SERVICE_DELETE_SUCCESS';

export const SERVICE_DELETE_ERROR = 'SERVICE_DELETE_ERROR';

export const SERVICE_UPDATE = 'SERVICE_UPDATE';

export const SERVICE_UPDATE_REQUEST = 'SERVICE_UPDATE_REQUEST';

export const SERVICE_UPDATE_SUCCESS = 'SERVICE_UPDATE_SUCCESS';

export const SERVICE_UPDATE_ERROR = 'SERVICE_UPDATE_ERROR';

export const SERVICE_CLEAR_STORE = 'SERVICE_CLEAR_STORE';

export const STATUS_UPDATE = 'STATUS_UPDATE';

export const STATUS_UPDATE_REQUEST = 'STATUS_UPDATE_REQUEST';

export const STATUS_UPDATE_SUCCESS = 'STATUS_UPDATE_SUCCESS';

export const STATUS_UPDATE_ERROR = 'STATUS_UPDATE_ERROR';
